config/routes.rb
Rails.application.routes.draw do
  post 'editor_images', to: 'editor_images#index'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers:
      {
          sessions: 'users/sessions',
          confirmations: 'users/confirmations',
          passwords: 'users/passwords',
          registrations: 'users/registrations',
          unlocks: 'users/unlocks',
          omniquth: 'users/omniquth'
      }

  # get 'home/index'

  resources :home, only: :index do
    collection do
      post :submit_contact_info
    end
  end

  get '/contact', to: 'home#contact'
  get '/faq', to: 'home#faq'
  get '/about-us', to: 'home#about_us', as: 'about_us'
  get '/privacy_and_policy', to: 'home#privacy_and_policy'
  get '/terms_and_conditions', to: 'home#terms_and_condition'
  get '/refund_policy', to: 'home#refund_policy'
  get '/mentor-schedules', to: 'schedule_booking#index', as: 'mentor_schedules'
  get '/booking-schedule', to: 'schedule_booking#booking_schedule', as: 'booking_schedule'
  post 'update_schedule_booking', to: 'schedule_booking#update_schedule_booking', as: 'update_schedule_booking'
  root 'home#index'

  resources :scholarships, only: [:index, :show]
  resources :services, only: :index
  resources :countries, only: [:index, :show]
  resources :blogs
  resources :comments

  scope :dashboard do
    get '/', to: "dashboard#index", as: :dashboard
    resources :student_applications
    resources :users do
      collection do
        get :my_profile
        get :edit_my_profile
        post :update_my_profile
        get :unconfirmed_user
        # get :request_for_new_mentorship
        # post :create_request_for_new_mentorship
      end
      member do
        get :lock
        get :unlock
        get :confirm
      end
    end
    resources :schedules do
      collection do
        get :booking_schedule
        get :booked_users
        get :cancel_schedule
      end
    end
    resources :payments, only: :index
  end

  get 'request-mentorship', to: 'users#request_for_new_mentorship', as: :request_for_new_mentorship
  post 'create-mentorship', to: 'users#create_request_for_new_mentorship', as: :create_request_for_new_mentorship

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  def index
    # flash[:success] = 'Dashboard'
    @total_schedules = Schedule.all.count
    @total_applications = StudentApplication.all.count
    @total_students = User.students.count
    # @total_admins = User.admins.count
    @total_unconfirmed_users = User.unconfirmed_users.count

    # @todays_schedules = Schedule.where("created_at=?", Date.today).count
    # @todays_applications = StudentApplication.where("created_at=?", Date.today).count
    @todays_schedules = Schedule.where(created_at: 1.days.ago..Time.current).count
    @todays_applications = StudentApplication.where(created_at: 1.days.ago..Time.current).count

    #only for mentor dashboard
    @mentor_total_schedules = current_user.mentor_schedules.count if current_user.mentor?
    @mentor_total_booked_schedules = current_user.mentor_schedules.student_schedules.count if current_user.mentor?

    #only for student dashboard
    @student_total_applications = current_user.student_applications.count if current_user.student?
    @student_total_schedules = current_user.student_schedules.count if current_user.student?

  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def current_class?(test_path)
    return 'is-active' if request.path == test_path
  end

  def current_class_same_path?(test_path, set_param, send_param )
    return 'is-active' if request.path == test_path && set_param == send_param
  end

  def header_class_define
    if controller.controller_name == 'users' && controller.action_name == 'request_for_new_mentorship'
      return ''
    else
      return 'o-page__content'
    end
  end

end

app/views/dashboard/_admin_dashboard.html.erb
<div class="row">
  <div class="col-md-6 col-xl-3">
    <%= link_to schedules_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--info u-mb-small">
        <i class="feather icon-activity"></i>
      </span>
        <h3 class="c-text--subtitle">Total Schedule</h3>
        <h1><%= @total_schedules %></h1>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3">
    <%= link_to student_applications_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--danger u-mb-small">
        <i class="feather icon-shopping-cart"></i>
      </span>
        <h3 class="c-text--subtitle">Total Application</h3>
        <h1><%= @total_applications %></h1>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3">
    <%= link_to users_path(type: :student) do %>
      <div class="c-card">
      <span class="c-icon c-icon--success u-mb-small">
        <i class="feather icon-users"></i>
      </span>
        <h3 class="c-text--subtitle">Total Students</h3>
        <h1><%= @total_students %></h1>
      </div>
    <% end %>
  </div>
  <% if can? :update, User%>
    <div class="col-md-6 col-xl-3">
      <%= link_to unconfirmed_user_users_path do %>
        <div class="c-card">
      <span class="c-icon c-icon--warning u-mb-small">
        <i class="feather icon-zap"></i>
      </span>
          <h3 class="c-text--subtitle">Unconfirm Users</h3>
          <h1><%= @total_unconfirmed_users %></h1>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="c-card u-ph-zero u-pb-zero">

      <div class="u-ph-medium">
        <h4>Today's Schedules</h4>
        <p>Activity from <%= Time.now.strftime("%d/%h/%y") %> 12:00 AM To <%= Time.now.strftime("%H:%M %P")  %></p>

        <span class="u-h1">
          <%= @todays_schedules %>
        </span>
      </div>

      <div class="u-p-medium">
        <div class="c-chart">
          <div class="sales-chart"></div>
        </div>
      </div>

    </div>
  </div>

  <div class="col-md-6">
    <div class="c-card u-ph-zero u-pb-zero">

      <div class="u-ph-medium">
        <h4>Today's Applications</h4>
        <p>Activity from <%= Time.now.strftime("%d/%h/%y") %> 12:00 AM To <%= Time.now.strftime("%H:%M %P")  %></p>

        <span class="u-h1">
          <%= @todays_applications %>
        </span>
      </div>

      <div class="u-p-medium">
        <div class="c-chart">
          <div class="payouts-chart"></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/dashboard/_director_admin_dashboard.html.erb
<div class="row">
  <div class="col-md-6 col-xl-3">
    <%= link_to schedules_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--info u-mb-small">
        <i class="feather icon-activity"></i>
      </span>
        <h3 class="c-text--subtitle">Total Schedule</h3>
        <h1><%= @total_schedules %></h1>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3">
    <%= link_to student_applications_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--danger u-mb-small">
        <i class="feather icon-shopping-cart"></i>
      </span>
        <h3 class="c-text--subtitle">Total Application</h3>
        <h1><%= @total_applications %></h1>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3">
    <%= link_to users_path(type: :student) do %>
      <div class="c-card">
      <span class="c-icon c-icon--success u-mb-small">
        <i class="feather icon-users"></i>
      </span>
        <h3 class="c-text--subtitle">Total Students</h3>
        <h1><%= @total_students %></h1>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3">
    <div class="c-card">
      <span class="c-icon c-icon--warning u-mb-small">
        <i class="feather icon-zap"></i>
      </span>
      <h3 class="c-text--subtitle">Admin</h3>
      <h1><%= @total_admins %></h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="c-card u-ph-zero u-pb-zero">

      <div class="u-ph-medium">
        <h4>Today's Schedules</h4>
        <p>Activity from <%= Time.now.strftime("%d/%h/%y") %> 12:00 AM To <%= Time.now.strftime("%H:%M %P")  %></p>

        <span class="u-h1">
          <%= @todays_schedules %>
        </span>
      </div>

      <div class="u-p-medium">
        <div class="c-chart">
          <div class="sales-chart"></div>
        </div>
      </div>

    </div>
  </div>

  <div class="col-md-6">
    <div class="c-card u-ph-zero u-pb-zero">

      <div class="u-ph-medium">
        <h4>Today's Applications</h4>
        <p>Activity from <%= Time.now.strftime("%d/%h/%y") %> 12:00 AM To <%= Time.now.strftime("%H:%M %P")  %></p>

        <span class="u-h1">3</span>
      </div>

      <div class="u-p-medium">
        <div class="c-chart">
          <div class="payouts-chart"></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/dashboard/_mentor_dashboard.html.erb
<div class="row">
  <div class="col-md-6 col-xl-3 text-center">
    <%= link_to new_schedule_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--info u-mb-small">
        <i class="feather icon-activity"></i>
      </span>
        <h3 class="c-text--subtitle">Create Schedule</h3>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3 text-center">
    <%= link_to new_student_application_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--danger u-mb-small">
        <i class="feather icon-shopping-cart"></i>
      </span>
        <h3 class="c-text--subtitle">Make Application</h3>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3 text-center">
    <%= link_to schedules_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--success u-mb-small">
        <i class="feather icon-users"></i>
      </span>
        <h3 class="c-text--subtitle">Your Schedules</h3>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3 text-center">
    <%= link_to booked_users_schedules_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--warning u-mb-small">
        <i class="feather icon-zap"></i>
      </span>
        <h3 class="c-text--subtitle">Booked Users</h3>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="c-card u-ph-zero u-pb-zero text-center">
      <div class="u-ph-medium">
        <h4>Your Total Schedules</h4>
        <span class="u-h1"><%= @mentor_total_schedules %></span>
      </div>
      <div class="u-p-medium">
        <div class="c-chart">
          <div class="sales-chart"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="c-card u-ph-zero u-pb-zero text-center">
      <div class="u-ph-medium">
        <h4>Your Booked Schedule</h4>
        <span class="u-h1"><%= @mentor_total_booked_schedules %></span>
      </div>
      <div class="u-p-medium">
        <div class="c-chart">
          <div class="payouts-chart"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_parent_dashboard.html.erb
parent

app/views/dashboard/_student_dashboard.html.erb
<div class="row">
  <div class="col-md-6 col-xl-3 text-center">
    <%= link_to users_path(:type => 'mentor') do %>
      <div class="c-card">
      <span class="c-icon c-icon--info u-mb-small">
        <i class="feather icon-activity"></i>
      </span>
        <h3 class="c-text--subtitle">Take A Schedule</h3>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3 text-center">
    <%= link_to new_student_application_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--danger u-mb-small">
        <i class="feather icon-shopping-cart"></i>
      </span>
        <h3 class="c-text--subtitle">Make Application</h3>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3 text-center">
    <%= link_to booked_users_schedules_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--success u-mb-small">
        <i class="feather icon-users"></i>
      </span>
        <h3 class="c-text--subtitle">Your Schedules</h3>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-xl-3 text-center">
    <%= link_to student_applications_path do %>
      <div class="c-card">
      <span class="c-icon c-icon--warning u-mb-small">
        <i class="feather icon-zap"></i>
      </span>
        <h3 class="c-text--subtitle">Your Applications</h3>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="c-card u-ph-zero u-pb-zero text-center">
      <div class="u-ph-medium">
        <h4>Your total schedules</h4>
        <span class="u-h1"><%= @student_total_schedules %></span>
      </div>
      <div class="u-p-medium">
        <div class="c-chart">
          <div class="sales-chart"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="c-card u-ph-zero u-pb-zero text-center">
      <div class="u-ph-medium">
        <h4>Your total applications</h4>
        <span class="u-h1"><%= @student_total_applications %></span>
      </div>
      <div class="u-p-medium">
        <div class="c-chart">
          <div class="payouts-chart"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= render 'admin_dashboard' unless current_user.mentor? or current_user.student? %>
<%= render 'mentor_dashboard' if current_user.mentor? %>
<%= render 'student_dashboard' if current_user.student? %>