config/routes.rb
Rails.application.routes.draw do
  post 'editor_images', to: 'editor_images#index'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers:
      {
          sessions: 'users/sessions',
          confirmations: 'users/confirmations',
          passwords: 'users/passwords',
          registrations: 'users/registrations',
          unlocks: 'users/unlocks',
          omniquth: 'users/omniquth'
      }

  # get 'home/index'

  resources :home, only: :index do
    collection do
      post :submit_contact_info
    end
  end

  get '/contact', to: 'home#contact'
  get '/faq', to: 'home#faq'
  get '/about-us', to: 'home#about_us', as: 'about_us'
  get '/privacy_and_policy', to: 'home#privacy_and_policy'
  get '/terms_and_conditions', to: 'home#terms_and_condition'
  get '/refund_policy', to: 'home#refund_policy'
  get '/mentor-schedules', to: 'schedule_booking#index', as: 'mentor_schedules'
  get '/booking-schedule', to: 'schedule_booking#booking_schedule', as: 'booking_schedule'
  post 'update_schedule_booking', to: 'schedule_booking#update_schedule_booking', as: 'update_schedule_booking'
  root 'home#index'

  resources :scholarships, only: [:index, :show]
  resources :services, only: :index
  resources :countries, only: [:index, :show]
  resources :blogs
  resources :comments

  scope :dashboard do
    get '/', to: "dashboard#index", as: :dashboard
    resources :student_applications
    resources :users do
      collection do
        get :my_profile
        get :edit_my_profile
        post :update_my_profile
        get :unconfirmed_user
        # get :request_for_new_mentorship
        # post :create_request_for_new_mentorship
      end
      member do
        get :lock
        get :unlock
        get :confirm
      end
    end
    resources :schedules do
      collection do
        get :booking_schedule
        get :booked_users
        get :cancel_schedule
      end
    end
    resources :payments, only: :index
  end

  get 'request-mentorship', to: 'users#request_for_new_mentorship', as: :request_for_new_mentorship
  post 'create-mentorship', to: 'users#create_request_for_new_mentorship', as: :create_request_for_new_mentorship

end

app/views/shared/_footer.html.erb
<!-- Start footer area -->
<footer id="footer" class="site-footer">
  <div class="footer-top-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2>Become A Part of Abroad Inquiry Community Today</h2>
        </div><!--/.col-lg-9-->
        <div class="col-lg-12 text-center">
          <%= link_to "get started As a Mentor", request_for_new_mentorship_path, class: "btn btn-default"%>
          <%= link_to "Apply for Study Abroad", '/users/sign_up', class: "btn btn-default"%>
          <%= link_to "Apply with Scholarship", '/scholarships', class: "btn btn-default"%>
        </div><!--/.col-lg-3-->
      </div><!--/.row-->
    </div><!--/.container-->
  </div><!--/.footer-top-area-->

  <!-- Start footer widgets area -->
  <div class="footer-widgets-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-sm-12 col-12">
          <div class="footer-newsletter footer-widget">
            <h4 class="footer-title">Disclaimer</h4>
            <p class="disclamer">
              Due to the immigration policy and periodic changes of the immigration rules, Abroad Inquiry is not assuring or confirming to the aspirants to get visa. In addition, to get admission, scholarship and visa depends on admission board, embassy or particular countries immigration policy. However, Abroad Inquiry’s aspirants have a higher chance to be successful because of our expert mentors are able to guide the aspirants in all aspects to get the admission and visa. As getting admission, scholarship and visa depends on candidate’s academic and professional profile, financial documents, motivation of application and embassy interview. Therefore, Abroad Inquiry is only guiding to the candidates through expert mentors so that the applicants get a better result of their application.

              Provided information of various countries through the website is not fully accurate. Therefore, Abroad Inquiry advises to the applicants to check the information from the relevant website.

              Last but not least, before aspirants apply through Abroad Inquiry, candidates are strongly advised to double check of our
              <%= link_to 'Refund policy', '/refund_policy' %>, <%= link_to ' privacy policy', '/privacy_and_policy' %> & <%= link_to 'terms and conditions', '/terms_and_conditions' %>.
            </p>
          </div><!--/.footer-newsletter-->
        </div>
      </div>

      <div class="row">
        <div class="col-lg-6 col-sm-6 col-6">
          <div class="footer-widget">
            <h4 class="footer-title">Quick Links</h4>
            <ul class="footer-widget-list list-unstyled">
              <li><a href="/contact">Contact</a></li>
              <li>
                <%= link_to 'About Us', about_us_path%>
              </li>
              <!--              <li><a href="#">About Us</a></li>-->
            </ul>
          </div><!--/.footer-widget-->
        </div><!--/.col-lg-3-->
        <div class="col-lg-6 col-sm-12">
          <div class="footer-newsletter footer-widget">
            <h4 class="footer-title">Abroad Inquiry Developer</h4>
            <p>This Webste is developed by Abroad Inquiry Developer Team, If you face any problem or want to give us a feedback or report, Please Click the Contact Us.</p>
            <a href="/contact" class="btn btn-default btn-primary">Contact Us</a>
          </div><!--/.footer-newsletter-->
        </div><!--/.col-lg-6-->
      </div><!--/.row-->
      <div class="row">
        <div class="col-lg-12">
          <div class="event-social-share text-center">
            <a href="https://www.facebook.com/Abroadinquiry/"><i class="fa fa-2x fa-facebook"></i></a>
            <a href="https://www.youtube.com/channel/UC449v3BZA6aSs9g8J__OZsw"><i class="fa fa-2x fa-youtube"></i></a>
            <a href="https://www.instagram.com/abroadinquiry"><i class="fa fa-2x fa-instagram"></i></a>
          </div>
        </div>
      </div>
    </div><!--/.container-->
  </div><!-- End footer widgets area -->
  <!-- Start footer copyright area -->
  <div class="footer-copyright-area bg-gray">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="copyright text-center">
            &copy; Copyrighted by <a href="https://www.abroadinquiry.com">Abroad Inquiry.</a>
            |
            <%= link_to 'Privacy and Policy', privacy_and_policy_path %>
            |
            <%= link_to 'Terms and Conditions', '/terms_and_conditions' %>
            |
            <%= link_to 'Login', '/users/sign_in' %>
            |
            <%= link_to 'Registration', '/users/sign_up' %>
          </div>
        </div>
      </div><!--/.row-->
    </div><!--/.container-->
  </div><!--End footer copyright area -->
</footer><!--End footer area -->

app/views/shared/_header.html.erb
<!--====Header Area
  ====================================-->
<!--<header id="site-header" class="header-area">-->
<!--  <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--    <a class="navbar-brand" href="/">-->
<!--      <%#= image_tag 'abroad-inquery-logo.png', size: '24x24', alt: 'logo' %> <span class="site-logo"><b>Abroad Inquiry</b></span>-->
<!--    </a>-->
<!--    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    <div class="collapse navbar-collapse" id="navbarNav">-->

<!--      <ul class="nav navbar-nav mr-auto">-->

<!--        <li class="nav-item">-->
          <%#= link_to 'Home', root_path, class: "nav-link c-nav-link" %>
<!--        </li>-->

<!--        <li class="nav-item">-->
          <%#= link_to 'Services', services_path, class: "nav-link c-nav-link" %>
<!--        </li>-->

<!--        <li class="nav-item">-->
          <%#= link_to 'Country', countries_path, class: "nav-link c-nav-link" %>
<!--        </li>-->

<!--        <li class="nav-item">-->
          <%#= link_to 'Scholarships', scholarships_path, class: "nav-link c-nav-link" %>
<!--        </li>-->

<!--        <li class="nav-item">-->
          <%#= link_to 'Blog', blogs_path, class: "nav-link c-nav-link" %>
<!--        </li>-->

<!--        <li class="nav-item">-->
          <%#= link_to 'About Us', about_us_path, class: "nav-link c-nav-link" %>
<!--        </li>-->
<!--      </ul>-->

<!--      <ul class="nav navbar-nav ml-auto">-->
        <%# unless user_signed_in? %>
<!--          <li class="nav-item">-->
            <%#= link_to 'Register', new_user_registration_path, class: "nav-link c-nav-link"%>
<!--          </li>-->

<!--          <li class="nav-item">-->
            <%#= link_to 'Login', new_user_session_path, class: "nav-link c-nav-link"%>
<!--          </li>-->
        <%# end %>

<!--        <li class="nav-item">-->
<!--          <a class="nav-link c-nav-link" href="/contact">contact</a>-->
<!--        </li>-->
        <%# if user_signed_in? %>
<!--          <li class="nav-item">-->
            <%#= link_to 'Dashboard', '/dashboard', class: "nav-link c-nav-link"%>
<!--          </li>-->
        <%# end %>
<!--      </ul>-->

<!--    </div>-->
<!--  </nav>-->
<!--</header>-->



<!--====Header Area
  ====================================-->
<header id="site-header" class="header-area">
  <div class="header-inner">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="logo-menu-wrap hidden-xs hidden-sm">
            <div class="logo">
              <a href="/">
                <%= image_tag 'abroad-inquery-logo.png', size: '24x24', alt: 'logo' %>
                <%#= image_tag 'logo.png', size: '24x24', alt: 'logo' %>
                <span><b>Abroad Inquiry</b></span>
              </a>
            </div><!--/.logo-->
            <nav class="menu">
              <ul id="nav">
                <li>
                  <%= link_to 'Home', root_path %>
                </li>

                <li>
                  <%= link_to 'Services', services_path %>
                </li>

                <li>
                  <%= link_to 'Country', countries_path %>
                </li>

                <li>
                  <%= link_to 'Scholarships', scholarships_path%>
                </li>
                <li>
                  <%= link_to 'Blog', blogs_path %>
                </li>

                <li>
                  <%= link_to 'About Us', about_us_path %>
                </li>

                <!--                <li class="dropdown-trigger"><a href="#">Faq</a>-->
                <!--                  <ul class="dropdown-content">-->
                <!--                    <li>-->
                <%#= link_to 'FAQ', faq_path %>
                <!--                    </li>-->
                <!--                    <li>-->
                <%#= link_to 'About Us', about_us_path %>
                <!--                    </li>-->
                <!--                  </ul>-->
                <!--                </li>-->
              </ul>
            </nav><!--/.menu-->
            <div class="register-contact-nav pull-right">
              <%#= link_to('Logout', destroy_user_session_path, method: :delete) if user_signed_in? %>
              <% unless user_signed_in? %>
                <div class="login">
                  <%= link_to 'Register', new_user_registration_path%>
                  <%= link_to 'Login', new_user_session_path%>
                </div>

                <a class="btn btn-default" href="/contact">contact</a>
              <% end %>
              <%= link_to 'Dashboard', '/dashboard', class: "btn btn-default" if user_signed_in?%>
            </div><!--/.register-contact-nav-->
          </div><!--/.logo-menu-wrap-->
        </div><!--/.col-lg-12-->
      </div><!--/.row-->
    </div><!--/.container-fluid-->
  </div><!--/.headier-inner-->

  <!--  <div id="sticky-header"></div>-->

  <!--Mobile Menu-->
  <div class="mobile-menu mean-container">
    <a class="mobile-logo" href="/">
      <%#= image_tag 'logo.png', alt: 'logo' %>
      <%= image_tag 'abroad-inquery-logo.png', size: '24x24', alt: 'logo' %>
      <%#= image_tag 'logo.png', size: '24x24', alt: 'logo' %>
      <span><b>Abroad Inquiry</b></span>
    </a>
  </div>
</header><!--/.header-area-->