config/routes.rb
Rails.application.routes.draw do
  post 'editor_images', to: 'editor_images#index'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers:
      {
          sessions: 'users/sessions',
          confirmations: 'users/confirmations',
          passwords: 'users/passwords',
          registrations: 'users/registrations',
          unlocks: 'users/unlocks',
          omniquth: 'users/omniquth'
      }

  # get 'home/index'

  resources :home, only: :index do
    collection do
      post :submit_contact_info
    end
  end

  get '/contact', to: 'home#contact'
  get '/faq', to: 'home#faq'
  get '/about-us', to: 'home#about_us', as: 'about_us'
  get '/privacy_and_policy', to: 'home#privacy_and_policy'
  get '/terms_and_conditions', to: 'home#terms_and_condition'
  get '/refund_policy', to: 'home#refund_policy'
  get '/mentor-schedules', to: 'schedule_booking#index', as: 'mentor_schedules'
  get '/booking-schedule', to: 'schedule_booking#booking_schedule', as: 'booking_schedule'
  post 'update_schedule_booking', to: 'schedule_booking#update_schedule_booking', as: 'update_schedule_booking'
  root 'home#index'

  resources :scholarships, only: [:index, :show]
  resources :services, only: :index
  resources :countries, only: [:index, :show]
  resources :blogs
  resources :comments

  scope :dashboard do
    get '/', to: "dashboard#index", as: :dashboard
    resources :student_applications
    resources :users do
      collection do
        get :my_profile
        get :edit_my_profile
        post :update_my_profile
        get :unconfirmed_user
        # get :request_for_new_mentorship
        # post :create_request_for_new_mentorship
      end
      member do
        get :lock
        get :unlock
        get :confirm
      end
    end
    resources :schedules do
      collection do
        get :booking_schedule
        get :booked_users
        get :cancel_schedule
      end
    end
    resources :payments, only: :index
  end

  get 'request-mentorship', to: 'users#request_for_new_mentorship', as: :request_for_new_mentorship
  post 'create-mentorship', to: 'users#create_request_for_new_mentorship', as: :create_request_for_new_mentorship

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @countries = Country.all.order(:name)
    @popular_countries = @countries.first(3)
    @popular_country_mentors = @popular_countries.collect {|c| c.users.mentors.first}
    @blogs = Blog.last(3)
  end

  def contact ;end

  def submit_contact_info
    ContactUsMailer.welcome_email(contact_params).deliver
    flash[:success] = 'Message has sent successfully!'
    redirect_to '/contact'
  end

  def faq ;end

  def about_us ;end

  def privacy_and_policy; end
  def refund_policy; end
  def terms_and_condition; end

  private
  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :subject, :message)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<section class="page-heading-section bg-image before-bg" style="background-image: url(<%= asset_path('header/p-header4.jpg') %>);">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="page-heading">
          <h2 class="page-name text-capitalize">about us</h2>
        </div><!--/.page-heading-->
      </div><!--/.col-md-12-->
    </div><!--/.row-->
  </div><!--/.container-->
</section><!--/.page-heading-area-->

<div class="about-page page-wrapper">
  <section id="standard-section" class="our-standard-section s-pd1">
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-lg-8">
          <div class="section-heading-area text-center">
            <h2 class="section-heading">Abroad Inquiry</h2>
          </div>
        </div><!--/.col-lg-8-->
      </div><!--/.row-->
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <div id="accordion" class="our-standard-content" role="tablist" aria-multiselectable="true">

            <div class="panel panel-default single-standard">
              <div id="collapseTwo" class="panel-collapse collapse show" role="tabpanel">
                <div class="single-standard-content">
                  <p>
                    Abroad Inquiry was born in 2017 from an altruist Facebook group which has helped hundreds of international students to pursue higher study from all around the world. Abroad Inquiry is a community-based platform runs by a group of International students from different countries. Why Abroad Inquiry was born? The common thing that we noticed that students are being provided with false information from unauthentic sources and it results in the refusal of their visa application. This is not a refusal; we think it’s a death of a dream. Here at our Abroad Inquiry, we provide all factual true information related to higher study abroad that we have acquired from our real-life experience and thorough researches. We believe that a current student who has already gone through the hectic process of study abroad journey, they can be the best source of information and understand the situation better than others and information obtained is more authentic compared to online sources or any other student consultancy firms. Thus, we have built this platform to help upcoming students.
                  </p>
                </div>
              </div><!--/.panel-collapse-->
            </div><!--/.single-standard-->


            <div class="panel panel-default single-standard">
              <div id="collapseTwo" class="panel-collapse collapse show" role="tabpanel">
                <div class="single-standard-content">
                  <p>
                    During our last three years of consecutive support provided to the aspirants, we have gathered a vast amount of experience in various problems which students usually face. Our mentors are already graduated from top notch universities of different countries and some of them are working at reputed companies who are working relentlessly to ease the journey of potential future students.
                  </p>
                  <p>
                    However, we took this decision to serve upcoming students because as being an international student, we experienced the same thing before going to a new place such as lack of information, difficulty in getting admission, preparation of necessary documents as per the requirement of respective university and visa consular office. We have an expert team of passionate individuals who are professional to make your dream of study abroad into a reality. Furthermore, we also provide comprehensive support to manage housing, part-time job, study guidelines, guidelines to get PR and so on.
                  </p>
                </div>
              </div><!--/.panel-collapse-->
            </div><!--/.single-standard-->

            <div class="panel panel-default single-standard">
              <div id="collapseTwo" class="panel-collapse collapse show" role="tabpanel">
                <div class="single-standard-content">
                  <p>
                    In a nutshell, our company provides complete support from admission to settlement in a foreign country. Students will get all the support and motivation from our mentors who run this company. Therefore, let’s get in touch with us from the very first day of your planning stage.
                  </p>
                </div>
              </div><!--/.panel-collapse-->
            </div><!--/.single-standard-->

          </div><!--/.our-standard-content-->
        </div><!--/.col-lg-6-->
      </div><!--/.row-->
    </div><!--/.container-->
  </section><!--/.page-heading-area-->
</div>

app/views/home/contact.html.erb
<!--=======Page Heading
   ==================================-->
<section class="page-heading-section bg-image before-bg" style="background-image: url(<%= asset_path('header/p-header1.jpg') %>);">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="page-heading">
          <h2 class="page-name text-capitalize">contact US</h2>
        </div><!--/.page-heading-->
      </div><!--/.col-md-12-->
    </div><!--/.row-->
  </div><!--/.container-->
</section><!--/.page-heading-area-->

<!--=======Contact Page
==================================-->
<div class="contact-page page-wrapper">
  <section class="contact-form-section bg-image s-pd100" style="background-image: url(<%= asset_path('contact-bg.jpg') %>);">
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-md-10">
          <%= form_tag(submit_contact_info_home_index_path, class: "contact-form-area border-radius", id:"contact-form") do %>
            <h3>Direct Message</h3>
            <div class="form-group">
              <%= text_field_tag 'contact[name]', nil, class:"form-control", id:"name", placeholder: "Your Full Name", required: true %>
            </div>
            <div class="form-group">
              <%= text_field_tag 'contact[phone]', nil, class:"form-control", id:"phone", placeholder: "Your Phone Number", required: true %>
            </div>
            <div class="form-group">
              <%= email_field_tag 'contact[email]', nil, class:"form-control", id:"email", placeholder: "Your Email", required: true %>
            </div>
            <div class="form-group">
              <%= text_field_tag 'contact[subject]', nil, class:"form-control", id:"subject", placeholder: "Your Subject", required: true %>
            </div>
            <div class="form-group">
              <%= text_area_tag 'contact[message]', nil, class:"form-control", id:"message", placeholder: "Message", required: true %>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          <% end %>
        </div>
      </div>
    </div>
  </section>


  <section class="contact-info-section s-pd100">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 col-6">
          <div class="single-contact-info box bg-gray text-center border-radius">
            <span class="fa fa-envelope"></span>
            <h3>Email</h3>
            <p>abroadinquiry.bd@gmail.com</p>
          </div><!--/.single-contact-info-->
        </div><!--/.col-lg-3-->
        <div class="col-lg-3 col-md-6 col-6">
          <div class="single-contact-info box bg-gray text-center border-radius">
            <span class="fa fa-phone"></span>
            <h3>phone</h3>
<!--            <p>+8801911248972</p>-->
            <p>+8801915-178576, +8801718-665274</p>
          </div><!--/.single-contact-info-->
        </div><!--/.col-lg-3-->
        <div class="col-lg-3 col-md-6 col-6">
          <div class="single-contact-info box bg-gray text-center border-radius">
            <span class="fa fa-globe"></span>
            <h3>facebook</h3>
            <p><a href="https://www.facebook.com/Abroadinquiry/">Abroadinquiry</a></p>
          </div><!--/.single-contact-info-->
        </div><!--/.col-lg-3-->
        <div class="col-lg-3 col-md-6 col-6">
          <div class="single-contact-info box bg-gray text-center border-radius">
            <span class="fa fa-map-marker"></span>
            <h3>address</h3>
            <p>
<!--              H#53, R#1, Niketon, Dhaka-1212, Bangladesh.-->
              Block# A, Road no.# 1, House no.#53 (Ground floor), Niketon, Gulshan 1, Dhaka - 1212
            </p>
          </div><!--/.single-contact-info-->
        </div><!--/.col-lg-3-->
      </div><!--/.row-->
    </div><!--/.container-->
  </section><!--/.contact-info-section-->
</div><!--/.contact-page-->

app/views/home/index.html.erb
<!--====Home Search Section
    ====================================-->
<div id="home-search-section" class="home-search-section-area bg-image home-header-one" style="background-image: url(<%= asset_path('welcome-bg.jpg')%>);">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="welcome-text text-center tb">
          <div class="tb-cell">
            <h1>Learn the factual study abroad information from experienced mentor</h1>
            <p>
              Get a mentor today and save your research time & get real-life authentic information from experienced mentor that you will never learn from unauthentic sources.
              We make sure to provide true experiences and hassle free service for your higher study abroad.
            </p>

            <%= form_tag mentor_schedules_path, class: "product-search-form", method: :get do%>
              <div class="form-group">
                <%#= text_field_tag :search, '', class: "form-controllar", placeholder: "Which country you want to go" %>
                <%= select_tag :country, options_from_collection_for_select(@countries, "id", "name"), class: "form-controllar", prompt: "Which country you want to go" %>
                <%= submit_tag :search, class: "btn btn-default btn-primary" %>
              </div>
            <% end %>

          </div><!--/.tb-cell-->
        </div><!--/.welcome-text-->
      </div><!--/.col-lg-12-->
    </div><!--/.row-->
  </div><!--/.container-->
</div><!--/#home-search-section-->

<!--====Services Section
====================================-->
<section id="services-section" class="services-section-area s-pd1">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-lg-8">
        <div class="section-heading-area text-center">
          <h2 class="section-heading text-capitalize">This is what we offer</h2>
          <p>
            Informing to the aspirants the factual information of a country and providing admission,
            scholarship and visa services for study abroad through expert mentors who already went through the process, became successful and living the country.
          </p>

        </div><!--/.section-heading-area-->
      </div><!--/.col-lg-8-->
    </div><!--/.row-->
    <div class="row">
      <div class="col-lg-4 col-md-4">
        <div class="single-service text-center">
          <div class="icon">
            <%= image_tag 'icon/PASSPORT ICON -02.png', size: '50x50', alt: 'icon' %>
          </div>
          <h3>Online Guidance Service</h3>
          <p class="services">Here you will get the full guidance and information for your selected country and you can book an
            appointment with our expert mentors from different countries.
            Later, you will talk with your chosen mentor over Skype for thirty minutes.
            The mentor will inform you of the factual information related to your subject, universities,
            country and part-time job facilities, financial matters, scholarships and relevant information. In addition, the mentor will analyze
            your profile and guide you to which university & scholarship suits your profile. Besides, you can ask as much as relevant questions.
            Does it seem like interested in talking with your desire mentor?
            Then you can <a href="/contact">contact us</a>
            or choose a <%= link_to :country, countries_path %> and select a mentor <a href="#">here</a>.
          </p>
        </div><!--/.single-service-->
      </div><!--/.col-lg-4-->
      <div class="col-lg-4 col-md-4">
        <div class="single-service text-center">
          <div class="icon">
            <%= image_tag 'icon/PASSPORT ICON -01.png', size: '50x50', alt: 'icon' %>
          </div><!--/.row-->
          <h3>Admission and Visa Service</h3>
          <p class="services">
            After meeting with your mentor, if you decided to further work with Abroad Inquiry, then you can apply through us.
            We will further guide you on how to arrange your paper, how to prepare your document for application. Consequently,
            we will apply for your admission and visa on behalf of you. Until you get your visa,
            we will take all of your responsibility to fulfill your higher study abroad dream.
            If you are interested, you can <a href="/contact">contact us</a> or request it <a href="#">here</a>.
          </p>
        </div><!--/.single-service-->
      </div><!--/.col-lg-4-->
      <div class="col-lg-4 col-md-4">
        <div class="single-service text-center">
          <div class="icon">
            <%= image_tag 'icon/PASSPORT ICON -03.png', size: '50x50', alt: 'icon' %>
          </div><!--/.row-->
          <h3>Scholarship and Visa Service</h3>
          <p class="services">
            Once you have decided to apply abroad with scholarship, our awarded scholars will assist you until you get your admission, scholarship and visa.
            As our mentors are living your desire country and have got the real life experiences from their field of interest and became successful,
            they will inform and guide you in all aspects such as how to write a killer motivation letter for scholarship,
            documents you need to arrange for scholarship, costs of application and so on.
            If you would like to apply for scholarship, then you can select a  <%= link_to :scholarship, scholarships_path %> and feel free to <a href="/contact">contact us</a>.
          </p>
        </div><!--/.single-service-->
      </div><!--/.col-lg-4-->
    </div><!--/.row-->
  </div><!--/.container-->
</section><!--/#services-section-->

<!--====Courses Section
====================================-->
<section id="courses-section" class="popular-courses-area bg-gray s-pd2">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-lg-8">
        <div class="section-heading-area text-center">
          <h2 class="section-heading text-capitalize">Popular Countries</h2>
        </div><!--/.section-heading-area-->
      </div><!--/.col-lg-8-->
    </div><!--/.row-->
    <!--    <div class="row">-->
    <!--      <div class="col-lg-12">-->
    <!--        <ul class="list-unstyled popular-filter-nav text-center">-->
    <!--          <li><a class="filter" href="#" data-filter="*">All</a></li>-->
    <!--          <li><a class="filter" href="#" data-filter=".design">Design</a></li>-->
    <!--          <li><a href="#" class="filter" data-filter=".development">Development</a></li>-->
    <!--          <li><a href="#" class="filter" data-filter=".business">Business</a></li>-->
    <!--          <li><a href="#" class="filter" data-filter=".photography">Photography</a></li>-->
    <!--        </ul>-->
    <!--      </div>-->
    <!--    </div>-->
    <div class="row courses-item-content">
      <% @popular_countries.each_with_index do |country, index| %>
        <div class="col-lg-4 col-sm-6 design photography">
          <!--Single Course Item Start-->
          <div class="single-course-item border-radius">
            <div class="course-content">
              <h2>
                <%= link_to country.name, mentor_schedules_path(country: country.id) %>
              </h2>
              <% if country.users.present? %>

                <div class="trainer-profile clearfix">
                  <%= image_tag @popular_country_mentors[index].image_url, class: "rounded-circle", alt: "img" if @popular_country_mentors[index].image.present?%>
                  <div class="trainer-info">
                    <h3><%= @popular_country_mentors[index].full_name %></h3>
                    <h3>Program: <%= @popular_country_mentors[index].occupation %></h3>
                    <p>City: <%= @popular_country_mentors[index].city_name %></p>
                    <p>University: <%= @popular_country_mentors[index].university %></p>
                  </div>
                  <div class="course-cat text-capitalize text-right">
                    <!--                            <a href="courses.html#">Schedules</a>-->
                    <%= link_to user_path(@popular_country_mentors[index]) do %>
                      Schedules
                    <% end %>
                  </div>
                </div>
              <% else %>
                <div class="trainer-profile clearfix">
                  <%= image_tag "author/author-1.jpg", class: "rounded-circle", alt: "img" %>
                  <div class="trainer-info">
                    <h3>Country has no Mentor</h3>
                  </div>
                </div><!--/.trainer-profile-->
              <% end %>
            </div><!--/.course-content-->
          </div><!--/.single-course-item-end-->
        </div><!--/.col-lg-4-->
      <% end %>
    </div><!--/.row-->
    <div class="row">
      <div class="col-lg-12">
        <div class="group-btn text-center">
          <a href="/users/sign_up" class="btn btn-default btn-primary">Apply for Study Abroad</a>
          <a href="/scholarships" class="btn btn-default">Apply with Scholarship</a>
        </div><!--/.form-group-btn-->
      </div><!--/.col-lg-12-->
    </div><!--/.row-->
  </div><!--/.container-->
</section><!--/#courses-section-->

<!--====Blog Section
====================================-->
<section id="blog-section" class="blog-section-area bg-gray s-pd2">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-lg-8">
        <div class="section-heading-area text-center">
          <h2 class="section-heading text-capitalize">Recent Blogs</h2>
        </div><!--/.section-heading-area-->
      </div><!--/.col-lg-8-->
    </div><!--/.row-->
    <div class="row">
      <!-- Start single blog -->

      <% if @blogs.present?  %>
        <% @blogs.each do |blog| %>
          <div class="col-md-4 col-sm-12">
            <div class="blog">
              <div class="blog-thumb">
                <%= image_tag image_url(blog.image), alt: "blog image", style: 'height: 200px' %>
              </div>
              <div class="blog-details">
                <div class="blog-time">
                  <span class="blog-date"><%= blog.created_at.strftime("%B %d %Y  %I:%M %P") %> By <a href="#"> <%= blog.admin_user.full_name %> </a></span>
                  <span class="blog__category">Category <a href="#"><%= blog.category.name %></a></span>
                </div>
                <div class="blog-title">
                  <h3>
                    <%= link_to blog_path(blog.id) do%>
                      <!--                          9 Ridiculous Rules About Tweets -->
                      <%= truncate(blog.title, length: 30) %>
                    <% end %>
                  </h3>

                </div>
                <p> <%= truncate(blog.short_body, length: 80)%></p>
                <div class="blog-more">
                  <%= link_to 'Read More', blog_path(blog.id), class: "btn btn-default" %>
                  <span class="blog-comments"><a href="#"><%= blog.comments.count %> comments</a></span>
                </div>
              </div>
            </div>
          </div>
        <%end %>
      <%else %>
        <div style="text-align: center; font-size: medium"> No Blog Found </div>
      <%end %>
      <!-- End single blog -->
    </div><!--/.row-->
    <div class="row">
      <div class="col-lg-12">
        <div class="blog-button text-center">
          <%= link_to 'go to blog', blogs_path, class: "btn btn-default btn-primary" %>
        </div>
      </div><!--/.col-lg-12-->
    </div><!--/.row-->
  </div><!--/.container-->
</section><!-- End blog area -->

<% content_for :javascript do %>
  <script type="text/javascript">
      $(document).ready(function() {
          $(".services").shorten({
              "showChars" : 150,
              "moreText"	: "See More",
              "lessText"	: "Less",
          });
      });
  </script>
<% end %>

app/views/home/privacy_and_policy.html.erb
<!--=======Page Heading
===============================================-->
<section class="page-heading-section before-bg bg-image" style="background-image: url(<%= asset_path('header/p-header4.jpg') %>);">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="page-heading">
          <h2 class="page-name text-capitalize">Privacy and Policy</h2>
        </div><!--/.page-heading-->
      </div><!--/.col-md-12-->
    </div><!--/.row-->
  </div><!--/.container-->
</section><!--/.page-heading-area-->


<div class="events-details-page page-wrapper s-pd100">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <article class="single-event-area">
          <h2>Refund Policy</h2>
          <div class="event-details">
            <h3><h3>
              Refund Policy and Service Charge Conditions:
            </h3>
              <p>
                Abroad Inquiry will refund the aspirant’s full registration charge if Abroad Inquiry fails to get the aspirant’s offer letter. 
                In case of visarefusal, Abroad Inquiry will not charge any fees for admission, visa, orregistration cost that Abroad Inquiry charge for
                services. However, if aspirants want to withdraw their application after submitting the paper and after registration from Abroad Inquiry,
                Abroad Inquiry will not refund the aspirant’s registration fees. Further, if Abroad Inquiry can accomplish the application and get the
                positive result (visa) of the application and the applicants do not want to go abroad for applicant’s personal circumstances or any issues,
                then Abroad Inquiry will still charge the service fees and the applicant bound to pay the service fees to Abroad Inquiry. 
                <b>In addition, Abroad Inquiry will not refund the aspirants appointment cost if the aspirants miss the meeting with
                  Abroad Inquiry’s mentor.</b>
                However, if Abroad Inquiry’s mentors miss the appointment with any aspirant, then the aspirant can further book an appointment with
                the same mentor or another mentor according to the applicant’s choice. Even the client can get refunded of the mentor’s appointment cost.
                If aspirants have any questions regarding refund policy and service charge policy, then do not hesitate to
                <a href="/contact" style="color: #ff7f45">contact</a> us. Thank you.
              </p>
            </h3>
          </div>
        </article><!--/.single-event-area-->
      </div><!--/.col-lg-8-->
    </div><!--/.row-->
  </div><!--/.container-->
</div><!--/.events-details-page-->