config/routes.rb
Rails.application.routes.draw do
  post 'editor_images', to: 'editor_images#index'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers:
      {
          sessions: 'users/sessions',
          confirmations: 'users/confirmations',
          passwords: 'users/passwords',
          registrations: 'users/registrations',
          unlocks: 'users/unlocks',
          omniquth: 'users/omniquth'
      }

  # get 'home/index'

  resources :home, only: :index do
    collection do
      post :submit_contact_info
    end
  end

  get '/contact', to: 'home#contact'
  get '/faq', to: 'home#faq'
  get '/about-us', to: 'home#about_us', as: 'about_us'
  get '/privacy_and_policy', to: 'home#privacy_and_policy'
  get '/terms_and_conditions', to: 'home#terms_and_condition'
  get '/refund_policy', to: 'home#refund_policy'
  get '/mentor-schedules', to: 'schedule_booking#index', as: 'mentor_schedules'
  get '/booking-schedule', to: 'schedule_booking#booking_schedule', as: 'booking_schedule'
  post 'update_schedule_booking', to: 'schedule_booking#update_schedule_booking', as: 'update_schedule_booking'
  root 'home#index'

  resources :scholarships, only: [:index, :show]
  resources :services, only: :index
  resources :countries, only: [:index, :show]
  resources :blogs
  resources :comments

  scope :dashboard do
    get '/', to: "dashboard#index", as: :dashboard
    resources :student_applications
    resources :users do
      collection do
        get :my_profile
        get :edit_my_profile
        post :update_my_profile
        get :unconfirmed_user
        # get :request_for_new_mentorship
        # post :create_request_for_new_mentorship
      end
      member do
        get :lock
        get :unlock
        get :confirm
      end
    end
    resources :schedules do
      collection do
        get :booking_schedule
        get :booked_users
        get :cancel_schedule
      end
    end
    resources :payments, only: :index
  end

  get 'request-mentorship', to: 'users#request_for_new_mentorship', as: :request_for_new_mentorship
  post 'create-mentorship', to: 'users#create_request_for_new_mentorship', as: :create_request_for_new_mentorship

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  def index
    # flash[:success] = 'Dashboard'
    @total_schedules = Schedule.all.count
    @total_applications = StudentApplication.all.count
    @total_students = User.students.count
    # @total_admins = User.admins.count
    @total_unconfirmed_users = User.unconfirmed_users.count

    # @todays_schedules = Schedule.where("created_at=?", Date.today).count
    # @todays_applications = StudentApplication.where("created_at=?", Date.today).count
    @todays_schedules = Schedule.where(created_at: 1.days.ago..Time.current).count
    @todays_applications = StudentApplication.where(created_at: 1.days.ago..Time.current).count

    #only for mentor dashboard
    @mentor_total_schedules = current_user.mentor_schedules.count if current_user.mentor?
    @mentor_total_booked_schedules = current_user.mentor_schedules.student_schedules.count if current_user.mentor?

    #only for student dashboard
    @student_total_applications = current_user.student_applications.count if current_user.student?
    @student_total_schedules = current_user.student_schedules.count if current_user.student?

  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def current_class?(test_path)
    return 'is-active' if request.path == test_path
  end

  def current_class_same_path?(test_path, set_param, send_param )
    return 'is-active' if request.path == test_path && set_param == send_param
  end

  def header_class_define
    if controller.controller_name == 'users' && controller.action_name == 'request_for_new_mentorship'
      return ''
    else
      return 'o-page__content'
    end
  end

end

app/views/shared/dashboard/_footer.html.erb
<div class="row">
  <div class="col-12">
    <footer class="c-footer">
      <p>© 2019-20 Abroad Inquary</p>
      <span class="c-footer__divider">|</span>
      <nav>
        <%= link_to 'Terms', '/terms_and_conditions', class: "c-footer__link" %>
        <%= link_to 'Privacy', privacy_and_policy_path, class: "c-footer__link" %>
        <a class="c-footer__link" href="/faq">FAQ</a>
        <a class="c-footer__link" href="/contact">Help</a>
      </nav>
    </footer>
  </div>
</div>

app/views/shared/dashboard/_header.html.erb
<header class="c-navbar u-mb-medium">
  <button class="c-sidebar-toggle js-sidebar-toggle">
    <i class="feather icon-align-left"></i>
  </button>

  <h2 class="c-navbar__title">Abroad Inquiry</h2>

<!--  <div class="c-dropdown dropdown u-mr-small">-->
<!--    <div class="c-notification has-indicator dropdown-toggle" id="dropdownMenuToggle1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="button">-->
<!--      <i class="c-notification__icon feather icon-message-circle"></i>-->
<!--    </div>-->
    <%#= render 'shared/dashboard/messages' %>
<!--  </div>-->

<!--  <div class="c-dropdown dropdown u-mr-medium">-->
<!--    <div class="c-notification has-indicator dropdown-toggle" id="dropdownMenuToggle2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="button">-->
<!--      <i class="c-notification__icon feather icon-bell"></i>-->
<!--    </div>-->
    <%#= render 'shared/dashboard/notifications' %>
<!--  </div>-->

  <div class="c-dropdown dropdown">
    <div class="c-avatar c-avatar--xsmall dropdown-toggle" id="dropdownMenuAvatar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="button">
      <% if current_user.image.present?  %>
        <%= image_tag  current_user.image_url, class: "c-avatar__img", alt: "Adam Sandler" %>
      <%else %>
        <%= image_tag  'user.png', class: "c-avatar__img", alt: "Adam Sandler" %>
      <%end %>
    </div>

    <div class="c-dropdown__menu has-arrow dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuAvatar">
      <a class="c-dropdown__item dropdown-item" href="<%= my_profile_users_path %>">View Profile</a>
      <a class="c-dropdown__item dropdown-item" href="<%= edit_my_profile_users_path %>">Edit Profile</a>
      <%= link_to('Logout', destroy_user_session_path, method: :delete,class: "c-dropdown__item dropdown-item") if user_signed_in? %>
    </div>
  </div>
</header>

app/views/shared/dashboard/_messages.html.erb
<div class="c-dropdown__menu c-dropdown__menu--large has-arrow dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuToggle1">
  <span class="c-dropdown__menu-header">
    Messages
  </span>
  <a class="c-dropdown__item dropdown-item" href="#">
    <div class="o-media">
      <div class="o-media__img u-mr-xsmall">
      <span class="c-avatar c-avatar--xsmall">
        <%= image_tag 'avatar1-72.jpg', class: "c-avatar__img", alt: "Adam Sandler" %>
      </span>
      </div>

      <div class="o-media__body">
        <p>Hey, Julia how are you doing. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat eius iste.</p>
      </div>
    </div>
  </a>

  <a class="c-dropdown__item dropdown-item" href="#">
    <div class="o-media">
      <div class="o-media__img u-mr-xsmall">
      <span class="c-avatar c-avatar--xsmall">
        <%= image_tag 'avatar1-72.jpg', class: "c-avatar__img", alt: "Adam Sandler" %>
      </span>
      </div>

      <div class="o-media__body">
        <p>Hey, Julia how are you doing. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat eius iste.</p>
      </div>
    </div>
  </a>

  <a class="c-dropdown__menu-footer">
    All Mentions
  </a>
</div>

app/views/shared/dashboard/_modal.html.erb
<div class="c-modal modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal2" aria-hidden="true" style="display: none;">
  <div class="c-modal__dialog modal-dialog" role="document">
    <div class="c-modal__content">
      <div class="c-modal__body">
        <span class="c-modal__close" data-dismiss="modal" aria-label="Close">
          <i class="feather icon-x"></i>
        </span>
<!--        <span class="c-icon c-icon--large u-mb-small">-->
<!--          <i class="feather icon-anchor"></i>-->
<!--        </span>-->

        <h3 class="u-mb-small" id="modal-title"></h3>
        <div class="u-mb-medium" id="modal-content-body">xxxx
        </div>
        <div class="o-line">
          <button class="c-btn c-btn--info c-btn--outline" data-dismiss="modal" aria-label="Close">Close</button>
          <button class="c-btn c-btn--info" id="modal-submit">Submit</button>
        </div>
      </div>
    </div><!-- // .c-modal__content -->
  </div><!-- // .c-modal__dialog -->
</div><!-- // .c-modal -->

app/views/shared/dashboard/_notifications.html.erb
<div class="c-dropdown__menu c-dropdown__menu--large has-arrow dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuToggle2">
  <span class="c-dropdown__menu-header">
    Notifications
  </span>
  <a class="c-dropdown__item dropdown-item" href="#">
    <div class="o-media">
      <div class="o-media__img u-mr-xsmall">
        <span class="c-icon c-icon--info c-icon--xsmall"><i class="feather icon-globe"></i></span>
      </div>

      <div class="o-media__body">
        <p>We've updated the Stripe Services agreement and its supporting terms. Your continueduse of Stripe's services.</p>
      </div>
    </div>
  </a>

  <a class="c-dropdown__item dropdown-item" href="#">
    <div class="o-media">
      <div class="o-media__img u-mr-xsmall">
        <span class="c-icon c-icon--danger c-icon--xsmall"><i class="feather icon-x"></i></span>
      </div>

      <div class="o-media__body">
        <p>We've updated the Stripe Services agreement and its supporting terms. Your continueduse of Stripe's services.</p>
      </div>
    </div>
  </a>

  <a class="c-dropdown__item dropdown-item" href="#">
    <div class="o-media">
      <div class="o-media__img u-mr-xsmall">
        <span class="c-icon c-icon--success c-icon--xsmall"><i class="feather icon-anchor"></i></span>
      </div>

      <div class="o-media__body">
        <p>We've updated the Stripe Services agreement and its supporting terms. Your continueduse of Stripe's services.</p>
      </div>
    </div>
  </a>

  <a class="c-dropdown__menu-footer">
    All Notifications
  </a>
</div>

app/views/shared/dashboard/_sidebar.html.erb
`<div class="o-page__sidebar js-page-sidebar">
  <aside class="c-sidebar">

    <!--for all user-->
    <div class="c-sidebar__brand">
      <a href="/dashboard">
        <%= image_tag 'abroad-inquery-logo.png', style: 'width: 52px; height: 50px; margin-left: 70px', alt: "Neat" %>
      </a>
    </div>

    <div class="c-sidebar__body">
      <ul class="c-sidebar__list">
        <!--for all user-->
        <li>
          <a class="c-sidebar__link <%= current_class?("/dashboard") %>" href="/dashboard">
            <i class="c-sidebar__icon feather icon-home"></i>Dashboards
          </a>
        </li>

        <!--for all user-->
        <li>
          <a class="c-sidebar__link <%= current_class_same_path?(users_path, params[:type], 'mentor') %>" href="<%= users_path(:type => 'mentor') %>">
            <i class="c-sidebar__icon feather icon-user-check"></i>Mentors
          </a>
        </li>

        <!--only who can show user profile-->
        <% if can? :read, User%>
          <% unless current_user.student? %>
            <li>
              <a class="c-sidebar__link <%= current_class_same_path?(users_path, params[:type], 'student') %>" href="<%= users_path(:type => 'student') %>">
                <i class="c-sidebar__icon feather icon-user"></i>Students
              </a>
            </li>
          <% end %>
        <% end %>

        <!--only who can read student application-->
        <% if can? :read, StudentApplication %>
          <li>
            <%= link_to student_applications_path, class: "c-sidebar__link #{current_class?(student_applications_path)}" do %>
              <i class="c-sidebar__icon feather icon-file-text"></i>Student Applications
            <% end %>
          </li>
        <% end %>

        <!--only who can create student application-->
        <% if can? :create, StudentApplication %>
          <li>
            <%= link_to new_student_application_path, class: "c-sidebar__link #{current_class?(new_student_application_path)}" do %>
              <i class="c-sidebar__icon feather icon-file-plus"></i>Make Application
            <% end %>
          </li>
        <% end %>

        <!--only student can not show this-->
        <% unless current_user.student?  %>
          <li>
            <%= link_to schedules_path, class: "c-sidebar__link #{current_class?(schedules_path)}" do %>
              <i class="c-sidebar__icon feather icon-clock"></i>Schedules
            <% end %>
          </li>
        <% end %>

        <!--only who can Create Schedule-->
        <% if can? :create, Schedule %>
          <li>
            <%= link_to new_schedule_path, class: "c-sidebar__link #{current_class?(new_schedule_path)} " do %>
              <i class="c-sidebar__icon feather icon-edit"></i>New Schedule
            <% end %>
          </li>
        <% end %>

        <!--only who can Read Schedule-->
        <% if can? :read, Schedule and !current_user.student? %>
          <li>
            <%= link_to booked_users_schedules_path, class: "c-sidebar__link #{current_class?(booked_users_schedules_path)}" do %>
              <i class="c-sidebar__icon feather icon-users"></i>Booked User
            <% end %>
          </li>
        <% end %>

        <!--only Student Can show this-->
        <% if current_user.student? %>
          <li>
            <%= link_to schedules_path, class: "c-sidebar__link #{current_class?(schedules_path)}" do %>
              <i class="c-sidebar__icon far fa-clock"></i>Booked Schedule
            <% end %>
          </li>
        <% end %>


        <% if can? :manage, User%>
            <li>
              <a class="c-sidebar__link" href="<%= users_path %>">
                <i class="c-sidebar__icon feather icon-user"></i>All Users
              </a>
            </li>
        <% end %>

        <!--For All User-->
        <li>
          <%= link_to payments_path, class: "c-sidebar__link #{current_class?(payments_path)}" do %>
            <i class="c-sidebar__icon fa fa-money"></i>Payments
          <% end %>
        </li>
      </ul>
    </div>

    <% if user_signed_in? %>
      <!--Only Signed in user can see this-->
      <%= link_to destroy_user_session_path, method: :delete, class: "c-sidebar__footer" do %>
        Logout <i class="c-sidebar__footer-icon feather icon-power"></i>
      <% end %>
    <% end %>
  </aside>
</div>`